# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('HM', 'Human'), ('EL', 'Elf'), ('OR', 'Orc'), ('DW', 'Dwarf'), ('WR', 'Werewolf')], max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='game_type',
            field=models.CharField(choices=[('SP', 'Simpleplay'), ('MP', 'Multiplay')], max_length=3),
        ),
    ]
