# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20170430_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='game_type',
            field=models.CharField(choices=[('SP', 'Simpleplay'), ('MP', 'Multiplay')], max_length=3),
        ),
    ]
